### ISSUE TITLE
torchtext dependency issue

### ISSUE THREAD

**Issue by sungmin9939** [zhizdev/mvdfusion#3]
Hi

Thanks for the great work!

I encountered below error 

> (base) root@39c632041e34:/workspace/code/mvdfusion# python demo.py -c configs/mvd_gso.yaml
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from pytorch_lightning import seed_everything
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 31, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'

which can be handled by changing the version of torchtext to 0.10.x (in current env is 0.12.0)
but when i try to reinstall torchtext the version of torch is automatically changed to older version
is it okay to use older version of torch?
and it would be thankful if you can let me the versions of packages you used

Thanks

**Comment by zhizdev** [comment]
Thanks for trying out the code! I dumped the versions of pytorch related packages from an environment that is working. 

I can't seem to find torchtext anywhere. But I assume yes older version of torch will work. 

I would also check out the environment in the colab demo, because it is a pretty lean installation on top of colab. 

```
# Name                    Version                   Build  Channel
python                    3.8.5                h7579374_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.4.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.0                    pypi_0    pypi
transformers              4.25.1                   pypi_0    pypi
```

**Comment by sungmin9939** [comment]
that's weird...
could you show me the list from `pip list | grep torch`?
it seems to be that pytorch-lightning use torchtext.legacy when importing packages

**Comment by zhizdev** [comment]
here!
```
pytorch-lightning           1.4.2
pytorch3d                   0.7.1
torch                       1.11.0
torch-ema                   0.3
torchaudio                  0.11.0
torchmetrics                0.6.0
torchvision                 0.12.0
```
